### ISSUE TITLE
Possible to monitor progress of individual files in folder?

### ISSUE THREAD

**Issue by WontSeeMeComin** [soto-project/soto-s3-file-transfer#11]
Using the `to: S3Folder(url:)` functionality, is it possible to somehow monitor individual file upload progress/completion? Seems like `whenComplete/Success` is only called upon the entire folder operation completion/failure. As someone new to Swift NIO, this would be really helpful info. Thanks!

**Comment by adam-fowler** [comment]
Sorry I haven't implemented anything like that yet. You can monitor progress is you are uploading a single file using the `S3File` functions with the `progress` closure but folders there is no support.

**Comment by WontSeeMeComin** [comment]
No worries, I appreciate the response! I'm just doing my cache updates at
the folder level and that seems to be fine. Tricky getting my head around
Futures.

**Comment by WontSeeMeComin** [comment]
Hey, just curious, if someone were to take a stab at implementing it, would you be open to a PR?

**Comment by adam-fowler** [comment]
Yes I would be open to a PR. 

I guess the way I'd see it is you'd need to collate how much data is going to be uploaded/downloaded and use that data along with the progress closure from the file to file functions. The `S3FileDescriptor` already includes a size so you don't need to worry about that one. You would need to add the file size to the `FileDescriptor` struct which are created in `listFiles(in folder: String)`.

Ah while writing this I remembered the one issue which put me off doing this. The folder upload does file upload in parallel ie multiple files are uploading at the same time, which will complicate the whole process. I guess you could create an array of progresses (one for each file) which you update and then every second call the folder to folder closure with the sum of all these progresses.

**Comment by WontSeeMeComin** [comment]
You are generous with your time and information. I've got two personal Swift projects happening right now but when I come up for air I'd love to see about providing a possible solution here. Thanks!

**Comment by adam-fowler** [comment]
@mackerel #15

**Comment by adam-fowler** [comment]
v0.4.0 has added a progress closure to the copy/sync folder functions
