### ISSUE TITLE
s3FileTransfer progress never reaches 1.0

### ISSUE THREAD

**Issue by masaldana2** [soto-project/soto-s3-file-transfer#12]
When observing a progress value of an upload or download progress number stops at. 0.98 or 0.99 

`        
let _ = s3FileTransfer.copy(
            from: inputFolder,
            to: S3File(url: zipUrl)!){ progress in
            self.uploadingProgress = progress
            print(progress)
            if progress > 0.98{
                print("Scan Images zip uploaded successfully")

            }
        }`

**Comment by adam-fowler** [comment]
I can add a call at the end to ensure the progress callback is called with 1.0 but you shouldn't be using the progress value as an indication the copy has finished. Use `whenComplete` on the `EventLoopFuture` returned by the function.
