### ISSUE TITLE
Accessing Progress Variable for use in UI

### ISSUE THREAD

**Issue by thatMacAdmin** [soto-project/soto-s3-file-transfer#14]
Im likely missing something, but I have written this function inside a class:

`func uploadUsingS3Transfer(path: URL, prefix: String, completion: @escaping (Result<Bool, MyError>) -> Void) {
        let s3 = createS3Client()
        let bucket = self.bucketList[self.environment] ?? String()
        let fileTransfer = S3FileTransferManager(s3: s3, threadPoolProvider: .createNew)
        
        let uploadFuture = fileTransfer.copy(from: path.path, to: S3File(url: "s3://\(bucket)/\(prefix)/\(path.lastPathComponent)")!) { progress in
            DispatchQueue.main.async {
                self.uploadProgress = progress
            }
        }
            
        uploadFuture.whenComplete { result in
            switch result {
            case .failure(let error):
                debugPrint(error)
                completion(.failure(Error.couldNotUploadFile))
            case .success:
                completion(.success(true))
            }
            
            s3.client.shutdown(queue: .main) { shutdown in }
        }
    }`

I have a progress bar which should monitor the upload progress and report it to the user but even though I can debug print out self.uploadProgress and its correct the variable (standard, published or state) never updates in the UI view. Im probably missing something related to Future Loops but thought id ask here first on the best way to work with this variable.

**Comment by adam-fowler** [comment]
Progress for uploading a folder is on my todo list. I just haven't implemented it yet. Currently progress update is only available for individual files.

**Comment by adam-fowler** [comment]
I have added progress functions for uploading to S3 and downloading from S3. You can find the changes in the `folder-update-progress` branch. Would you be able to test this for me?

**Comment by adam-fowler** [comment]
@thatMacAdmin Did you get anywhere with this?

**Comment by adam-fowler** [comment]
v0.4.0 has added a progress closure to the copy/sync folder functions
