### ISSUE TITLE
Uploading a folder includes all folder in path

### ISSUE THREAD

**Issue by tcollins590** [soto-project/soto-s3-file-transfer#20]
When uploading a folder to a S3Folder, all of the folders in the path are created in the S3 folder that is uploaded. Is there a way to upload only the last folder in the URL string?

```
let uploadFuture = s3FileTransfer.copy(
    from: "/Users/me/images/", 
    to: S3Folder(url: "s3://my-bucket/images/")!
)
```

The resulting uploaded folder path is "s3://my-bucket/images/Users/me/images/"
The desired uploaded folder structure is "s3//my-bucket/images/"

**Comment by adam-fowler** [comment]
Sorry I'm not seeing this. I even have a test to verify this doesn't happen `testCopyPathLocalToS3`. It verifies that the root folder is not included in the S3 path.

What version of soto-s3-file-transfer are you using and also what platform are you running this on?

**Comment by adam-fowler** [comment]
@tylercollins590 was this across a symbolic link? If so v0.4.2 should fix this

**Comment by adam-fowler** [comment]
closing as I've had no response
