### ISSUE TITLE
Need file size sync also

### ISSUE THREAD

**Issue by HaiderAli008** [soto-project/soto-s3-file-transfer#23]
Can you please add in sync feature if the size of file change on amazon then local file also change according to ?

**Comment by HaiderAli008** [comment]
Due to network or other reason if video file downloaded partially its not updated next time and video file remain corrupt until delete

**Comment by adam-fowler** [comment]
Hi @HaiderAli008 This should be possible. But there is the possibility that this could delete files that are newer on the destination even though they are newer. Is this what you intend?

**Comment by HaiderAli008** [comment]
At cloud storage side I need to replace file with some changes that is not synch with local folder because of file already exist  and also some time internet issue some file does't download properly and it remain corrupt.

**Comment by HaiderAli008** [comment]
And also library not support to upload zip file.

**Comment by adam-fowler** [comment]
Hi @HaiderAli008 
If I gave you a function that resumed a download that failed would that work for you?

**Comment by adam-fowler** [comment]
See PR #33 
Code works as follows
```swift
// resume failed download
func resume(_ download: S3FileTransferManager.DownloadOperation) async {
    do {
        try await self.s3FileTransfer.resume(download: download)
    } catch {
        if let error = error as? S3FileTransferManager.Error, case .downloadFailed(_, let download) = error {
            await self.resume(download)
        }
    }
}

do {
    try await self.s3FileTransfer.sync(from: self.s3Folder, to: self.localFolder, delete: true)
} catch {
    if let error = error as? S3FileTransferManager.Error, case .downloadFailed(_, let download) = error {
        await self.resume(download)
    }
}
```

**Comment by adam-fowler** [comment]
Closing as I've had no response
