### ISSUE TITLE
TaskQueue change to async/await

### ISSUE THREAD

**Issue by VineFiner** [soto-project/soto-s3-file-transfer#26]
Planned TaskQueue changed to Asynchronous Sequences?

**Comment by adam-fowler** [comment]
Yes there are plans I just haven't got around to it. I do have an async implementation of TaskQueue here https://github.com/adam-fowler/async-collections/blob/main/Sources/AsyncCollections/TaskQueue.swift

**Comment by adam-fowler** [comment]
2.0.0 beta is out which is written completely in Swift Concurrency
