### ISSUE TITLE
serial uploading

### ISSUE THREAD

**Issue by mpkupriyanov** [soto-project/soto-s3-file-transfer#27]
Hi Adam

I create files .ts and try upload them serially. 
Have some priorities for uploading FIFO?

I use func Copy from local file, to S3 file

set maxConcurrentTasks = 1, doesn't help me. New files started uploading. It seems doesn't work like needed

```
let configuration = S3FileTransferManager.Configuration(maxConcurrentTasks: 1)
self.s3FileTransferManager = S3FileTransferManager(s3: s3Client, threadPoolProvider: .createNew, configuration: configuration)
```
![Screenshot 2022-07-10 at 13 00 00](https://user-images.githubusercontent.com/8414491/178140183-214d7960-07b7-4ee7-a60b-77387dcc3ef9.png)

use Soto S3 Transfer version 1.0.0

**Comment by mpkupriyanov** [comment]
when installed Soto S3 Transfer version 0.4.2
uploading good working

**Comment by adam-fowler** [comment]
Hi, can you post your code doing the uploads. 

The task queue config only really affects folder uploads. I guess I could push single uploads through the task queue but there are other methods to ensure uploads are done serially.

**Comment by adam-fowler** [comment]
Closing as I've had no response
