### ISSUE TITLE
S3FileTransferManager always crashing on deinit

### ISSUE THREAD

**Issue by whitemarten** [soto-project/soto-s3-file-transfer#29]
Trying any of the samples from the README, `deinit` of `S3FileTransferManager` will always crash with an assertion.
This happens even when calling `syncShutdown` on the manager when using `threadPoolProvider: .createNew`.

Not sure if there is any modification to `internal let isShutdown` which is supposed to be `true` on `deinit`.

**Comment by adam-fowler** [comment]
you need to call `syncShutdown` before the `S3FileTransferManager` is deleted

**Comment by whitemarten** [comment]
I did... like I wrote.

**Comment by adam-fowler** [comment]
Sorry I completely missed that.

**Comment by adam-fowler** [comment]
Fixed in #31 
Added tests so we'll catch it next time
