### ISSUE TITLE
Expose S3FileTransferManager.listFiles publicly

### ISSUE THREAD

**Issue by genkernel** [soto-project/soto-s3-file-transfer#40]
Would you consider declaring existing `S3FileTransferManager.listFiles()` public?
I have a use case that requires listing files before taking an action on selected item(s) (e.g. select which files to download from remote).
Thanks!

**Comment by adam-fowler** [comment]
Which ListFiles? The one that lists files in S3 or the one that lists files in your local file system? 

Both functions are fairly simple. You could just copy their contents.

**Comment by genkernel** [comment]
S3 ListFiles to list remote files.
I would like to rely on the source directly however would follow your advice to copy an implementation if you decide not to update.

**Comment by genkernel** [comment]
@adam-fowler would you be open to a pull request from me declaring the func `public`?

**Comment by adam-fowler** [comment]
Ok go ahead.

**Comment by genkernel** [comment]
Great thanks!
Pull request: https://github.com/soto-project/soto-s3-file-transfer/pull/41
Closing this.
