### ISSUE TITLE
Update readme to reflect dropping of NIO?

### ISSUE THREAD

**Issue by vade** [soto-project/soto-s3-file-transfer#44]
Hi

Im new to Soto and the ecosystem, so bear with me if I get this wrong!

Since Soto 7 dropped NIO and is using structured concurrency features of Swift, it seems like this repo's readme may need some updating? 

If not, feel free to ignore!

**Comment by adam-fowler** [comment]
Fair comment. We haven't dropped NIO though, it just an implementation detail now and futures no longer appear in our public API
