### ISSUE TITLE
Help with Error -65554: NoSuchRecord during File Upload

### ISSUE THREAD

**Issue by gaedokan** [soto-project/soto-s3-file-transfer#46]
Thank you for providing the SDK! I’m currently working on implementing file upload as described in the documentation, but I’m encountering an error: `-65554: NoSuchRecord`. I’m unsure of what might be causing this issue and would greatly appreciate any guidance or suggestions on how to resolve it.

Thanks!

Here’s my current implementation for the file upload:

```
public struct S3Credentials: Equatable {
    public let accessKeyId: String
    public let secretAccessKey: String
    public let region: String

    public init(accessKeyId: String, secretAccessKey: String, region: String) {
        self.accessKeyId = accessKeyId
        self.secretAccessKey = secretAccessKey
        self.region = region
    }
}

enum S3UploaderActorError: Error {
    case pathConstructionFailed
}

final actor S3UploaderActor: GlobalActor {

    static let shared = S3UploaderActor()

    public static func upload(
        credentials: S3Credentials,
        from inputPath: String,
        to s3Path: String
    ) async throws {
        let client = AWSClient(
            credentialProvider: .static(accessKeyId: credentials.accessKeyId, secretAccessKey: credentials.secretAccessKey)
        )

        defer { try? client.syncShutdown() }

        let s3 = S3(client: client, region: Region(rawValue: credentials.region))
        let s3FileTransfer = S3FileTransferManager(s3: s3)

        guard let s3File = S3File(url: s3Path) else {
            throw S3UploaderActorError.pathConstructionFailed
        }

        do {
            let value = try await s3FileTransfer.copy(from: inputPath.dropPrefix("file://"), to: s3File)
        } catch {
           // error
        }
    }
}
```

**Comment by adam-fowler** [comment]
I can't find any details on a `NoSuchRecord` error in the AWS docs. If you output the error as "\(error)" it sometimes gives more information. Are you sure it is `NoSuchRecord` and not something like `NoSuchKey`?
Is it the call to  `s3FileTransfer.copy()` that is generating this error?
Have you verified that you inputPath is correct?

**Comment by gaedokan** [comment]
> 1. Are you sure it is NoSuchRecord and not something like NoSuchKey?

Yes, I am sure it's the "NoSuchRecord" error, not "NoSuchKey."

> 2. Is it the call to s3FileTransfer.copy() that is generating this error?

Yes, the error occurs during the call to s3FileTransfer.copy().

> 3. Have you verified that your inputPath is correct?

Initially i was passing the full path with a file:// prefix but I encountered an error. Afterward i made sure to send just the file path without the file:// which i assume should be correct

**Comment by gaedokan** [comment]
I printed the localized error description:
`The operation couldn’t be completed. (Network.NWError error -65554 - NoSuchRecord)`

**Comment by adam-fowler** [comment]
NoSuchRecord is a DNS lookup fail. Are you sure you have the correct bucket name?

**Comment by gaedokan** [comment]
I had a bit of a mix-up with the region 🤐. I was creating the region from a string like `CA_WEST_1` instead of the actual region name `ca-west-1`. Thanks a bunch for your help with this!
