### ISSUE TITLE
Update swift-nio to latest version

### ISSUE THREAD

**Issue by gaedokan** [soto-project/soto-s3-file-transfer#47]
Hi,

When using soto-s3-file-transfer, a thread checker warning appears. The latest version of swift-nio addresses this issue. Updating Soto-Core to depend on the latest swift-nio version should resolve the warning.

Here’s the [link to the swift-nio issue](https://github.com/apple/swift-nio/pull/2964).

Let me know if I can assist with this update!

Thanks!

**Comment by adam-fowler** [comment]
I'd be happy to accept a PR

**Comment by gaedokan** [comment]
I’ve begun updating the transitive dependencies for the first target, [soto-core](https://github.com/soto-project/soto-core/pull/630?new_mergebox=true). I’ll take care of the rest individually.

**Comment by gaedokan** [comment]
Could you please @adam-fowler release a new version for Soto-core? I’d like to update Soto and [soto-s3-file-transfer](https://github.com/soto-project/soto-s3-file-transfer) later on. Thanks a bunch!

**Comment by adam-fowler** [comment]
I have a number of other changes I am just finalizing. I'll do a release once they are ready.

**Comment by gaedokan** [comment]
I will await the release 🙏🏼
