### ISSUE TITLE
The package product 'SotoS3' requires minimum platform version 12.0 for the iOS platform, but this target supports 9.0

### ISSUE THREAD

**Issue by faisalalt** [soto-project/soto-s3-file-transfer#8]
I get this error message on xcode when adding "https://github.com/soto-project/soto-s3-file-transfer" to swift package manager. I checked and my IOS deployment version is 14.1 not 9. This does not happen when I use "https://github.com/soto-project/soto". Why is this happending with this repository

**Comment by adam-fowler** [comment]
I believe there is a fix for this on the main branch. Just haven't done a release with it in.
