### ISSUE TITLE
how to use on vapor

### ISSUE THREAD

**Issue by VineFiner** [soto-project/soto-s3-file-transfer#9]
File transfer is usually time-consuming, how does this work with vapor?

**Comment by adam-fowler** [comment]
@VineFiner Your question is a little vague. What size files are you transferring, where are you transferring them from and to? Is this something that might be better resolved by supplying your client with a pre-signed URL for upload?

**Comment by VineFiner** [comment]
I am sorry. I am interested in NextCloud. But it is not clear how to combine Vapor and s3. Do file management. 
Large files may be uploaded and downloaded.

**Comment by adam-fowler** [comment]
Are you wanting to provide upload and download capabilities to clients? If so your best route is to have your Vapor server generate a pre-signed URL for the upload or download and send that back to your client. They can then use this URL to perform the action. See https://soto.codes/2020/12/presigned-urls.html

If you want to perform S3 actions directly on your server. I would probaby not use `soto-s3-file-transfer` and use the `s3` library from https://github.com/soto-project/soto. The following gives you guidance on how to integrate aws services with Vapor https://soto.codes/user-guides/using-soto-with-vapor.html

**Comment by VineFiner** [comment]
Yes, I want to perform S3 operations directly on the server. Do you have any good recommendations?

**Comment by VineFiner** [comment]
Thanks, I will close it.
